version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: enotedb
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data



